### ISSUE TITLE
Issue loading Qt platform plugin "xcb" even though it was found

### ISSUE THREAD

**Issue by 07minkim** [dfaker/stable-diffusion-webui-cv2-external-masking-script#11] opened 2022-11-09 01:26 UTC
Hi, I'm trying to run this on a Runpod instance, and I'm getting the following error when I'd normally be getting the pop up window to draw the in-paint mask:

```
2022-11-09T01:07:53.915324047Z qt.qpa.xcb: could not connect to display 
2022-11-09T01:07:53.915377495Z qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/venv/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
2022-11-09T01:07:53.915385461Z This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
2022-11-09T01:07:53.915391214Z 
2022-11-09T01:07:53.915395674Z Available platform plugins are: xcb.
```

Before I installed the script, I had run "python -m pip install opencv-python" as instructed in the readme, and I had gotten the following message. Trying "python -m pip install --upgrade opencv-python" now also returns the same message:

```
Requirement already satisfied: opencv-python in /venv/lib/python3.10/site-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.19.3 in /venv/lib/python3.10/site-packages (from opencv-python) (1.23.4)
```

When I go to the /venv/lib/python3.10/site-packages/cv2/qt/plugins/platforms/ folder and type in "dir", I see that it does have a file named "libqxcb.so". 

I was wondering if you had any clues about what might be causing the issue here. TBH I find in-paint so cumbersome as almost not worth doing without this tool.

**Comment by dfaker** [comment] 2022-11-13 03:03
Seems to be using the `opencv-python-headless` version without gui support, try: 

```
py -m pip uninstall opencv-python-headless
py -m pip uninstall opencv-python
py -m pip install --upgrade opencv-python
```

**Comment by 07minkim** [comment] 2022-11-15 14:53
> Seems to be using the `opencv-python-headless` version without gui support, try:
> 
> ```
> py -m pip uninstall opencv-python-headless
> py -m pip uninstall opencv-python
> py -m pip install --upgrade opencv-python
> ```

Thank you for looking into this! When I tried running the 1st line, I got the following:

> WARNING: Skipping opencv-python-headless as it is not installed.

I did try running the other lines, uninstalling Opencv-Python and re-installing it, and I continue getting the same error as before.

**Comment by dfaker** [comment] 2022-11-15 15:05
Can we try this against the venv too rather than just the system level python, from the stable-diffusion-webui folder:

```
venv\Scripts\python -m pip uninstall opencv-python-headless
venv\Scripts\python -m pip uninstall opencv-python
venv\Scripts\python -m pip install --upgrade opencv-python
```

**Comment by dfaker** [comment] 2022-11-18 10:34
closing as duplicate of #13

**Closed as completed by dfaker** 2022-11-18 10:34 UTC
